export const TOGGLE_SHOP_MENU = 'TOGGLE_SHOP_MENU';
export const TOGGLE_CART_MENU = 'TOGGLE_CART_MENU';
export const TOGGLE_SEARCH_MENU = 'TOGGLE_SEARCH_MENU';
export const TOGGLE_QUICK_VIEW_MENU = 'TOGGLE_QUICK_VIEW_MENU';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const WEB3_PENDING = 'WEB3_PENDING';
export const WEB3_INITIALIZED = 'WEB3_INITIALIZED';
export const WEB3_FAILED = 'WEB3_FAILED';

export const OPEN_SIGNIN_MODAL = 'OPEN_SIGNIN_MODAL';
export const CLOSE_SIGNIN_MODAL = 'CLOSE_SIGNIN_MODAL';