export const TOGGLE_SHOP_MENU = 'TOGGLE_SHOP_MENU';
export const TOGGLE_CART_MENU = 'TOGGLE_CART_MENU';
export const TOGGLE_SEARCH_MENU = 'TOGGLE_SEARCH_MENU';
export const TOGGLE_QUICK_VIEW_MENU = 'TOGGLE_QUICK_VIEW_MENU';